### ISSUE TITLE
Jar dowload

### ISSUE THREAD

**Issue by Moura8** [gunterweb/sonar-pdf-plugin#1]
Hi. Where can i download the .jar?

**Comment by timeforarchi** [comment]
Hi,

you have to build it using Maven.
But be careful of your Sonar version

**Comment by Moura8** [comment]
Hi Gunter.
thank you for you quickly reply.
The mvn compile works like charm, however mvn package fails one test the following output:


17:03:00.212 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
17:03:00.215 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request
17:03:00.216 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request
17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)
17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request
Tests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.345 sec <<< FAILURE! - in TestSuite
metricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)  Time elapsed: 0.44 sec  <<< FAILURE!
org.sonarqube.ws.connectors.ConnectionException: Query: org.apache.commons.httpclient.methods.GetMethod@4c6e276e
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at org.sonarqube.ws.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:104)
        at org.sonarqube.ws.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:91)
        at org.sonarqube.ws.client.WSClient.find(WSClient.java:74)
        at org.sonar.report.pdf.builder.MeasuresBuilder.getAllMetricKeys(MeasuresBuilder.java:84)
        at org.sonar.report.pdf.test.MetricsTest.metricsShouldBeConsistent(MetricsTest.java:41)


Results :

Failed tests:
  MetricsTest.metricsShouldBeConsistent:41 » Connection Query: org.apache.common...



Tests run: 5, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.434 s
[INFO] Finished at: 2018-07-06T17:03:00+00:00

**Comment by timeforarchi** [comment]
hi the test checks that your local sonar is ok with the api and metrics. so you have to define one in localhost 9000
-------- Message d'origine --------De : Moura8 <notifications@github.com> Date : 06/07/2018  19:11  (GMT+01:00) À : gunterweb/sonar-pdf-plugin <sonar-pdf-plugin@noreply.github.com> Cc : Bontemps Fabien <fab.bontemps@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [gunterweb/sonar-pdf-plugin] Jar dowload (#1) 
Hi Gunter.

thank you for you quickly reply.

The mvn compile works like charm, however mvn package fails one test the following output:
17:03:00.212 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

17:03:00.215 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request

17:03:00.216 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request

17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request

Tests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.345 sec <<< FAILURE! - in TestSuite

metricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)  Time elapsed: 0.44 sec  <<< FAILURE!

org.sonarqube.ws.connectors.ConnectionException: Query: org.apache.commons.httpclient.methods.GetMethod@4c6e276e

at java.net.PlainSocketImpl.socketConnect(Native Method)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)

at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)

at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)

at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)

at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)

at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)

at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)

at org.sonarqube.ws.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:104)

at org.sonarqube.ws.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:91)

at org.sonarqube.ws.client.WSClient.find(WSClient.java:74)

at org.sonar.report.pdf.builder.MeasuresBuilder.getAllMetricKeys(MeasuresBuilder.java:84)

at org.sonar.report.pdf.test.MetricsTest.metricsShouldBeConsistent(MetricsTest.java:41)
Results :
Failed tests:

MetricsTest.metricsShouldBeConsistent:41 » Connection Query: org.apache.common...
Tests run: 5, Failures: 1, Errors: 0, Skipped: 1
[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 5.434 s

[INFO] Finished at: 2018-07-06T17:03:00+00:00

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gunterweb/sonar-pdf-plugin","title":"gunterweb/sonar-pdf-plugin","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/gunterweb/sonar-pdf-plugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Moura8 in #1: Hi Gunter.\r\nthank you for you quickly reply.\r\nThe mvn compile works like charm, however mvn package fails one test the following output:\r\n\r\n\r\n17:03:00.212 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)\r\n17:03:00.215 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request\r\n17:03:00.216 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)\r\n17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request\r\n17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)\r\n17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request\r\nTests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.345 sec \u003c\u003c\u003c FAILURE! - in TestSuite\r\nmetricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)  Time elapsed: 0.44 sec  \u003c\u003c\u003c FAILURE!\r\norg.sonarqube.ws.connectors.ConnectionException: Query: org.apache.commons.httpclient.methods.GetMethod@4c6e276e\r\n        at java.net.PlainSocketImpl.socketConnect(Native Method)\r\n        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\r\n        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\r\n        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\r\n        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\r\n        at java.net.Socket.connect(Socket.java:589)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n        at java.lang.reflect.Method.invoke(Method.java:498)\r\n        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)\r\n        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)\r\n        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)\r\n        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)\r\n        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)\r\n        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)\r\n        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)\r\n        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)\r\n        at org.sonarqube.ws.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:104)\r\n        at org.sonarqube.ws.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:91)\r\n        at org.sonarqube.ws.client.WSClient.find(WSClient.java:74)\r\n        at org.sonar.report.pdf.builder.MeasuresBuilder.getAllMetricKeys(MeasuresBuilder.java:84)\r\n        at org.sonar.report.pdf.test.MetricsTest.metricsShouldBeConsistent(MetricsTest.java:41)\r\n\r\n\r\nResults :\r\n\r\nFailed tests:\r\n  MetricsTest.metricsShouldBeConsistent:41 » Connection Query: org.apache.common...\r\n\r\n\r\n\r\nTests run: 5, Failures: 1, Errors: 0, Skipped: 1\r\n\r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] BUILD FAILURE\r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] Total time: 5.434 s\r\n[INFO] Finished at: 2018-07-06T17:03:00+00:00\r\n"}],"action":{"name":"View Issue","url":"https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032",
"url": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [gunterweb/sonar-pdf-plugin] Jar dowload (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Moura8**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Moura8",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"gunterweb/sonar-pdf-plugin\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"gunterweb/sonar-pdf-plugin\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353737205\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by timeforarchi** [comment]
sorry forgot this one.you have to define the server url in test resources (file test.properties) and the key of the project in sonar you want to test. 
-------- Message d'origine --------De : Moura8 <notifications@github.com> Date : 06/07/2018  19:11  (GMT+01:00) À : gunterweb/sonar-pdf-plugin <sonar-pdf-plugin@noreply.github.com> Cc : Bontemps Fabien <fab.bontemps@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [gunterweb/sonar-pdf-plugin] Jar dowload (#1) 
Hi Gunter.

thank you for you quickly reply.

The mvn compile works like charm, however mvn package fails one test the following output:
17:03:00.212 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

17:03:00.215 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request

17:03:00.216 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request

17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)

17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request

Tests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.345 sec <<< FAILURE! - in TestSuite

metricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)  Time elapsed: 0.44 sec  <<< FAILURE!

org.sonarqube.ws.connectors.ConnectionException: Query: org.apache.commons.httpclient.methods.GetMethod@4c6e276e

at java.net.PlainSocketImpl.socketConnect(Native Method)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:589)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)

at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)

at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)

at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)

at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)

at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)

at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)

at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)

at org.sonarqube.ws.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:104)

at org.sonarqube.ws.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:91)

at org.sonarqube.ws.client.WSClient.find(WSClient.java:74)

at org.sonar.report.pdf.builder.MeasuresBuilder.getAllMetricKeys(MeasuresBuilder.java:84)

at org.sonar.report.pdf.test.MetricsTest.metricsShouldBeConsistent(MetricsTest.java:41)
Results :
Failed tests:

MetricsTest.metricsShouldBeConsistent:41 » Connection Query: org.apache.common...
Tests run: 5, Failures: 1, Errors: 0, Skipped: 1
[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 5.434 s

[INFO] Finished at: 2018-07-06T17:03:00+00:00

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gunterweb/sonar-pdf-plugin","title":"gunterweb/sonar-pdf-plugin","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/gunterweb/sonar-pdf-plugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Moura8 in #1: Hi Gunter.\r\nthank you for you quickly reply.\r\nThe mvn compile works like charm, however mvn package fails one test the following output:\r\n\r\n\r\n17:03:00.212 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)\r\n17:03:00.215 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request\r\n17:03:00.216 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)\r\n17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request\r\n17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused (Connection refused)\r\n17:03:00.217 INFO  o.a.c.httpclient.HttpMethodDirector - Retrying request\r\nTests run: 5, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.345 sec \u003c\u003c\u003c FAILURE! - in TestSuite\r\nmetricsShouldBeConsistent(org.sonar.report.pdf.test.MetricsTest)  Time elapsed: 0.44 sec  \u003c\u003c\u003c FAILURE!\r\norg.sonarqube.ws.connectors.ConnectionException: Query: org.apache.commons.httpclient.methods.GetMethod@4c6e276e\r\n        at java.net.PlainSocketImpl.socketConnect(Native Method)\r\n        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)\r\n        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)\r\n        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)\r\n        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\r\n        at java.net.Socket.connect(Socket.java:589)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n        at java.lang.reflect.Method.invoke(Method.java:498)\r\n        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)\r\n        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)\r\n        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)\r\n        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)\r\n        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)\r\n        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)\r\n        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)\r\n        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)\r\n        at org.sonarqube.ws.connectors.HttpClient3Connector.executeRequest(HttpClient3Connector.java:104)\r\n        at org.sonarqube.ws.connectors.HttpClient3Connector.execute(HttpClient3Connector.java:91)\r\n        at org.sonarqube.ws.client.WSClient.find(WSClient.java:74)\r\n        at org.sonar.report.pdf.builder.MeasuresBuilder.getAllMetricKeys(MeasuresBuilder.java:84)\r\n        at org.sonar.report.pdf.test.MetricsTest.metricsShouldBeConsistent(MetricsTest.java:41)\r\n\r\n\r\nResults :\r\n\r\nFailed tests:\r\n  MetricsTest.metricsShouldBeConsistent:41 » Connection Query: org.apache.common...\r\n\r\n\r\n\r\nTests run: 5, Failures: 1, Errors: 0, Skipped: 1\r\n\r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] BUILD FAILURE\r\n[INFO] ------------------------------------------------------------------------\r\n[INFO] Total time: 5.434 s\r\n[INFO] Finished at: 2018-07-06T17:03:00+00:00\r\n"}],"action":{"name":"View Issue","url":"https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032",
"url": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [gunterweb/sonar-pdf-plugin] Jar dowload (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Moura8**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Moura8",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"gunterweb/sonar-pdf-plugin\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"gunterweb/sonar-pdf-plugin\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403094032"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353737205\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Moura8** [comment]
Thank you, the first problems are resolved with your help.
Now im getting: 

13:28:51.099 INFO  org.sonar.PDF - Can't retrieve project info. Have you set username/password in Sonar settings?
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.389 sec <<< FAILURE! - in TestSuite
getReportTest(org.sonar.report.pdf.test.PDFGeneratorTest)  Time elapsed: 0.19 sec  <<< FAILURE!
org.sonar.report.pdf.entity.exception.ReportException: Can't retrieve project info. Parent project node is empty. Authentication?


What are im missing?

**Comment by timeforarchi** [comment]
Did you set the test properties including host user password and project key as I said through my last message ?
Fab
-------- Message d'origine --------De : Moura8 <notifications@github.com> Date : 09/07/2018  15:29  (GMT+01:00) À : gunterweb/sonar-pdf-plugin <sonar-pdf-plugin@noreply.github.com> Cc : Bontemps Fabien <fab.bontemps@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [gunterweb/sonar-pdf-plugin] Jar dowload (#1) 
Thank you, the first problems are resolved with your help.

Now im getting:
13:28:51.099 INFO  org.sonar.PDF - Can't retrieve project info. Have you set username/password in Sonar settings?

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.389 sec <<< FAILURE! - in TestSuite

getReportTest(org.sonar.report.pdf.test.PDFGeneratorTest)  Time elapsed: 0.19 sec  <<< FAILURE!

org.sonar.report.pdf.entity.exception.ReportException: Can't retrieve project info. Parent project node is empty. Authentication?
What are im missing?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gunterweb/sonar-pdf-plugin","title":"gunterweb/sonar-pdf-plugin","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/gunterweb/sonar-pdf-plugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Moura8 in #1: Thank you, the first problems are resolved with your help.\r\nNow im getting: \r\n\r\n13:28:51.099 INFO  org.sonar.PDF - Can't retrieve project info. Have you set username/password in Sonar settings?\r\nTests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.389 sec \u003c\u003c\u003c FAILURE! - in TestSuite\r\ngetReportTest(org.sonar.report.pdf.test.PDFGeneratorTest)  Time elapsed: 0.19 sec  \u003c\u003c\u003c FAILURE!\r\norg.sonar.report.pdf.entity.exception.ReportException: Can't retrieve project info. Parent project node is empty. Authentication?\r\n\r\n\r\nWhat are im missing?"}],"action":{"name":"View Issue","url":"https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403479297"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403479297",
"url": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403479297",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [gunterweb/sonar-pdf-plugin] Jar dowload (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Moura8**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Moura8",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"gunterweb/sonar-pdf-plugin\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"gunterweb/sonar-pdf-plugin\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/gunterweb/sonar-pdf-plugin/issues/1#issuecomment-403479297"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353737205\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Moura8** [comment]
Yes both in ./target/test-classes/test.properties and /src/test/resources/test.properties i put my configuration to enter in sonar webpage and the project key.
sonar.base.url=http://localhost:9000
sonar.base.login=userLogin
sonar.base.password=passwordLogin
front.page.logo=sonar.png
sonar.projectKey=trunk-project

In my pom.xml , last lines shoud are the credentials to my postgres db righr? The id is the name of database?

<profile>
                        <id>sonar</id>
                        <properties>
                                <sonar.jdbc.username>DBuser</sonar.jdbc.username>
                                <sonar.jdbc.password>DBpass</sonar.jdbc.password>
                        </properties>
                </profile>
